# Generated by Django 3.0.7 on 2021-01-23 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number length must be 11', regex='^\\w{11}$')]),
        ),
    ]
