# Generated by Django 3.0.7 on 2021-01-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeservice',
            name='evailable',
            field=models.BooleanField(default=True),
        ),
    ]
