# Generated by Django 3.0.7 on 2021-01-26 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='lab',
            field=models.ManyToManyField(to='user.Lab'),
        ),
        migrations.AddField(
            model_name='test',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Lab'),
        ),
        migrations.AddField(
            model_name='test',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.TestType'),
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
