# Generated by Django 3.0.7 on 2021-01-26 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210126_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Your order in the way to lab'), (1, 'Your order is pending in lab'), (2, 'Your order is ready in lab'), (3, 'Your order in the way to you')]),
        ),
        migrations.AlterField(
            model_name='test',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.TestType'),
        ),
    ]
