# Generated by Django 3.0.7 on 2021-01-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0003_auto_20210127_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtype',
            name='lab',
            field=models.ManyToManyField(related_name='testtypes', to='user.Lab'),
        ),
    ]
