# Generated by Django 3.0.7 on 2021-01-27 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210127_2048'),
        ('order', '0004_auto_20210127_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.BloodExpert'),
        ),
    ]
